import 'package:equatable/equatable.dart';

enum LocationQualityStatus {
  valid,
  suspicious,
  invalid,
  stale,
  outOfOrder
}

enum LocationSource {
  localNative,
  remoteTraccar,
  uiFallback
}

class NativeLocationEvent extends Equatable {
  final double latitude;
  final double longitude;
  final DateTime recordedAt; // Time generated by the native GPS (UTC)
  final DateTime receivedAt; // Time received by Flutter (UTC)
  final double speedMetersPerSecond; // Raw speed in m/s from the OS
  final double bearingDegrees;
  final double altitudeMeters;
  final double accuracyMeters;
  final LocationSource source;
  final String platform;
  final bool isMock;
  final LocationQualityStatus qualityStatus;

  const NativeLocationEvent({
    required this.latitude,
    required this.longitude,
    required this.recordedAt,
    required this.receivedAt,
    required this.speedMetersPerSecond,
    required this.bearingDegrees,
    required this.altitudeMeters,
    required this.accuracyMeters,
    required this.source,
    required this.platform,
    required this.isMock,
    required this.qualityStatus,
  });

  NativeLocationEvent copyWith({
    LocationQualityStatus? qualityStatus,
  }) {
    return NativeLocationEvent(
      latitude: latitude,
      longitude: longitude,
      recordedAt: recordedAt,
      receivedAt: receivedAt,
      speedMetersPerSecond: speedMetersPerSecond,
      bearingDegrees: bearingDegrees,
      altitudeMeters: altitudeMeters,
      accuracyMeters: accuracyMeters,
      source: source,
      platform: platform,
      isMock: isMock,
      qualityStatus: qualityStatus ?? this.qualityStatus,
    );
  }

  @override
  List<Object?> get props => [
        latitude,
        longitude,
        recordedAt,
        receivedAt,
        speedMetersPerSecond,
        bearingDegrees,
        altitudeMeters,
        accuracyMeters,
        source,
        platform,
        isMock,
        qualityStatus,
      ];
}
